workflows:
  ios-ipa-build:
    name: iOS IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: development # or app_store if you're publishing
        bundle_identifier: com.cuvette.riideMobileApp # Replace with your Bundle ID
      vars:
        XCODE_WORKSPACE: "riide_mobile_app.xcworkspace"
        XCODE_SCHEME: "riide_mobile_app"
      xcode: 15.3
      cocoapods: default
    scripts:
      - name: Install CocoaPods
        script: pod install
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
